### ISSUE TITLE
Extra credit - daymet pmap

### ISSUE THREAD

**Issue by leombastos** [leombastos/2024_dsa#24]

**Comment by Leoanish** [comment]
pmap <- extracred %>% 
  mutate(map = pmap(
    list(
      .site = site,
      .lat = lat,
      .lon = lon,
      .year = year
    ),
    function(.site, .lat, .lon, .year)
      download_daymet(site = .site,
                              lat = .lat,
                              lon = .lon,
                              start = .year,
                              simplify = T)
  ))

**Comment by Reneliza** [comment]
daymet_extracred <- extracred %>% 
 mutate = ex(pmap(
    list (download_daymet(.site = field$site[[1]],
                              .lat = field$lat[[1]],
                              .lon = field$lon[[1]],
                              .start = field$year[[1]],
                             . end = field$year[[1]]),
    function(.site, .lat, lon,start,end) %>%
      pivot_wider(names_from = measurement,
              values_from = value
              )

**Comment by aleenarayamajhi** [comment]
![Screenshot 2024-03-26 104337](https://github.com/leombastos/2024_dsa/assets/126793934/36db4165-7272-4821-b892-2f0015821655)
