### ISSUE TITLE
Assignment #1 

### ISSUE THREAD

**Issue by leombastos** [leombastos/2024_dsa#4]

**Comment by Promode45** [comment]
![plot1_a1_Hegde](https://github.com/leombastos/2024_dsa/assets/76169027/4024bd7f-0e88-49bb-b0ea-7bd5124f8055)

**Comment by Reneliza** [comment]
![plot_a1_CEJALVO](https://github.com/leombastos/2024_dsa/assets/128764190/b2d0c046-b5e7-4061-b710-7e3248e039d1)

**Comment by Leoanish** [comment]
![plot_a1_bhattarai](https://github.com/leombastos/2024_dsa/assets/122309367/3a8eb8ff-2c98-4872-b30d-fba84e75bf96)

**Comment by jn78616** [comment]
![plot_a1_Neupane](https://github.com/leombastos/2024_dsa/assets/156246575/306e34ab-01d9-4115-8236-a37e3ed7fc94)

**Comment by nietersc** [comment]
![plot_a1_NIETERS](https://github.com/leombastos/2024_dsa/assets/83737648/f7e73511-687e-4ac2-b413-90bdd890cafe)

**Comment by nietersc** [comment]
![plot_a1_NIETERS](https://github.com/leombastos/2024_dsa/assets/83737648/a8cf2d64-ae6e-47ae-98c6-7f47e8f7b837)

**Comment by thapashekhar** [comment]
![plot1](https://github.com/leombastos/2024_dsa/assets/97544018/fcdfd61f-44c9-4220-a690-96fd24b6eaed)

**Comment by aleenarayamajhi** [comment]
![plot_a1_Rayamajhi](https://github.com/leombastos/2024_dsa/assets/126793934/c754d75e-ad44-4406-b6fd-ec9b6090ba49)

**Comment by NivaIbrahim** [comment]
![plot_a1_Niva](https://github.com/leombastos/2024_dsa/assets/152580189/a4f4c505-4466-4be7-ba72-6785beda0845)

**Comment by JSCG95** [comment]
![image](https://github.com/leombastos/2024_dsa/assets/106388895/580ebceb-a4fa-4f96-92f8-9640ad8f1318)

**Comment by Binitaghimir** [comment]
![plot2](https://github.com/leombastos/2024_dsa/assets/156105170/9f9dc8cf-5d5c-433a-8cda-d04caff3e2e0)

**Comment by SultanNawaz** [comment]
![plot_a1_Nawaz](https://github.com/leombastos/2024_dsa/assets/156105107/314efab3-b104-4c84-b0cc-2cdf509110af)

**Comment by ujjwalsigdel** [comment]
![plot1](https://github.com/leombastos/2024_dsa/assets/123664580/2da77eb0-da32-4ac8-a68f-fa1b8ba2b73d)

**Comment by SoilDawg** [comment]
![plot_a1_SUBEDI](https://github.com/leombastos/2024_dsa/assets/156104880/42bd7f8d-6328-4217-b566-6d18fa7c77f8)

**Comment by ss59095** [comment]
![plot_a1_SHRESTHA](https://github.com/leombastos/2024_dsa/assets/155988308/5ad86b20-9894-46e8-8c2b-1be66a37dbc9)

**Comment by MuhammadUsmanK** [comment]
![plot_a1_khalid](https://github.com/leombastos/2024_dsa/assets/96457786/b3502935-506a-469a-9ba1-590338897d94)

**Comment by MuhammadUsmanK** [comment]
![image](https://github.com/leombastos/2024_dsa/assets/96457786/2215bb68-2fb5-48c6-abee-e69b078bfbf6)

**Comment by tsodhi1** [comment]
![plot_a1_Sodhi](https://github.com/leombastos/2024_dsa/assets/156205111/8742f039-55f7-40a4-906d-c3b23cb92bb1)

**Comment by ujjwalsigdel** [comment]
![plot_a1_Sigdel](https://github.com/leombastos/2024_dsa/assets/123664580/f54f3975-755f-4909-b101-0b758baac073)
