### ISSUE TITLE
Issue for Assignment #1

### ISSUE THREAD

**Issue by austinwinkler** [leombastos/2024_dsa#5]
![image](https://github.com/leombastos/2024_dsa/assets/122289166/cea26ff3-b99e-4f18-8c50-94c2671e5ba2)

Error in 'palette()`:

Not sure why, any help is appreciated

**Comment by Reneliza** [comment]
Hi, Austin. I think that using **scale_color_manual** requires you to specify a color for each category. I tried the script on the screenshot and it worked. Don't forget to add quotation marks to the words coz I encountered an error without them.
<img width="915" alt="Screenshot 2024-01-11 at 12 02 44 PM" src="https://github.com/leombastos/2024_dsa/assets/128764190/d394ea1c-383d-4b75-bbd2-5a9e44c65b99">

**Comment by Jazib001** [comment]
<img width="804" alt="Screenshot 2024-02-12 at 11 36 44 AM" src="https://github.com/leombastos/2024_dsa/assets/156104871/e7be6fe9-8812-42f4-845a-4f954afb3e41">
<img width="804" alt="Screenshot 2024-02-12 at 11 37 16 AM" src="https://github.com/leombastos/2024_dsa/assets/156104871/0eb0ae99-b690-4408-bcc6-07c353909098">

in both cases, I am getting different yields, is it okay to just go with one of the plots for combined NK effects on yield ?
